# 'store_id': {'store_name': , 'store_category': , 'sub_categories': }

categories = {
    'womensclothing': "Women's Clothing",
    'girlsclothing': "Girls' Clothing",
    'babyclothing': "Baby Clothing",
    'boysclothing': "Boys' Clothing",
    'mensclothing': "Men's Clothing",
    'standard': 'Standard Screen',
    'imax': 'IMAX Screen',
    'asian': 'Asian',
    'sandwiches': 'Burgers & Sandwiches',
    'mexican': 'Mexican',
    'pizza': 'Pizza',
    'mediterranean': 'Mediterranean',
    'snacks': 'Snacks',
    'juice': 'Juices & Smoothies',
    'womensshoes': "Women's Shoes",
    'mensshoes': "Men's Shoes",
    'purses': "Purses",
    'neckwear': "Neckwear",
    'cellphones': "Cell Phones",
    'computers': "Computers",
    'phoneaccessories': "Phone accessories",
    'videogames': "Video Games",
    'internetprov': "Internet Providers",
    'home': "Home",
    'pets': "Pets",
    'books': "Books",
    'collectibles': "Collectible Items",
    'miscgifts': "Miscellaneous Gifts",
    'musicalinst': "Musical Instruments",
    'photography': "Photography",
    'toys': "Toys",
    'cologneperfume': "Cologne & Perfume",
    'hair': "Hair",
    'health': "Health",
    'nails': "Nails",
    'everyday': "Everyday Jewelry",
    'watches': "Watches",
    'fine': "Fine Jewelry",
    }

stores = {
    '2love': {
        'store_name': '2 Love', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkey': '2Love',
        },
    '2loveshoes': {
        'store_name': '2 Love Shoes', 
        'store_category': 'shoes', 
        'sub_categories': ['womensshoes'],
        'mapkey': '???',
        },  
    '2020': {
        'store_name': '20/20', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkey': '20/20'
        },
    'accesoryshop': {
        'store_name': 'The Accesory Shop', 
        'store_category': 'accessories', 
        'sub_categories': ['purses'],
        'mapkey': 'TheAccessoryShop',
        },  
    'asianapps': {
        'store_name': 'Asian Apps +', 
        'store_category': 'food', 
        'sub_categories': ['asian'],
        'mapkey': 'AsianApp +',
        },
    'att': {
        'store_name': 'AT&T', 
        'store_category': 'electronics', 
        'sub_categories': ['cellphones'],
        'mapkey': 'outside',
        },
    'bathbodyworks': {
        'store_name': 'Bath & Body Works', 
        'store_category': 'home', 
        'sub_categories': ['home'],
        'mapkey': 'Bath and Body Works',
        },  
    'bazzar': {
        'store_name': 'The Bazzar', 
        'store_category': 'gifts', 
        'sub_categories': ['miscgifts'],
        'mapkey': 'TheBazzar',
        },
    'bbb': {
        'store_name': 'Bed Bath & Beyond', 
        'store_category': 'home', 
        'sub_categories': ['home'],
        'mapkey': 'BedBathBeyond',
        },
    'boost': {
        'store_name': 'Boost Mobile', 
        'store_category': 'electronics', 
        'sub_categories': ['cellphones'],
        'mapkey': 'BoostMobile',
        },
    'browspa24': {
        'store_name': 'Brow Spa 24', 
        'store_category': 'healthandbeauty', 
        'sub_categories': ['nails'],
        'mapkey': 'BrowSpa24',
        },
    'caferio': {
        'store_name': 'Cafe Rio', 
        'store_category': 'food', 
        'sub_categories': ['mexican'],
        'mapkey': 'outside',
        },
    'cafezupas': {
        'store_name': 'Cafe Zupas', 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkey': 'outside',
        },
    'cellagain': {
        'store_name': 'Cell Again', 
        'store_category': 'electronics', 
        'sub_categories': ['phoneaccessories'],
        'mapkey': 'CellAgain',
        },
    'centurylink': {
        'store_name': 'CenturyLink', 
        'store_category': 'electronics', 
        'sub_categories': ['internetprov'],
        'mapkey': '???',
        },
    'charleysalon': {
        'store_name': 'Charley Salon', 
        'store_category': 'healthandbeauty', 
        'sub_categories': ['hair'],
        'mapkey': 'CharleySalon',
        },
    'childrensplace': {
        'store_name': "The Children's Place", 
        'store_category': 'clothing', 
        'sub_categories': ['boysclothing', 'girlsclothing', 'babyclothing'],
        'mapkey': 'outside',
        },
    'chinesegourmetexpress': {
        'store_name': 'Chinese Gourmet Express', 
        'store_category': 'food', 
        'sub_categories': ['asian'],
        'mapkey': 'ChineseGourmetExpress',
        },
    'churrosolepizzeria': {
        'store_name': "Churro's Ole' Pizzeria", 
        'store_category': 'food', 
        'sub_categories': ['pizza'],
        'mapkey': 'ChurrosPizzaria',
        },
    'claires': {
        'store_name': "Claire's", 
        'store_category': 'accessories', 
        'sub_categories': ['purses'],
        'mapkey': 'Claires',
        },  
    'cricket': {
        'store_name': 'Cricket Wireless', 
        'store_category': 'electronics', 
        'sub_categories': ['cellphones'],
        'mapkey': '???',
        },
    'dcwesternwear': {
        'store_name': "DC Western Wear", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'mensclothing'],
        'mapkey': '???',
        },
    'deseretbook': {
        'store_name': 'Deseret Book', 
        'store_category': 'gifts', 
        'sub_categories': ['books'],
        'mapkey': 'outside',
        },
    'diamondwireless': {
        'store_name': 'Diamond Wireless', 
        'store_category': 'electronics', 
        'sub_categories': ['cellphones'],
        'mapkey': 'DiamondWireless',
        },
    'deseretbook': {
        'store_name': 'Deseret Book', 
        'store_category': 'gifts', 
        'sub_categories': ['books'],
        'mapkey': 'outside',
        },
    'edible': {
        'store_name': 'Edible Arrangements', 
        'store_category': 'gifts', 
        'sub_categories': ['miscgifts'],
        'mapkey': 'outside',
        },
    'fadsnfashions': {
        'store_name': "Fads N' Fashions", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing'],
        'mapkey': 'FadsNFashions',
        },
    'famousfootwear': {
        'store_name': 'Famous Footwear', 
        'store_category': 'shoes', 
        'sub_categories': ['womensshoes', 'mensshoes'],
        'mapkey': 'FamousFootwear',
        },  
    'fanzz': {
        'store_name': 'Fanzz', 
        'store_category': 'clothing', 
        'sub_categories': ['mensclothing', 'boysclothing'],
        'mapkey': 'Fanzz',
        },
    'footaction': {
        'store_name': 'Foot Action', 
        'store_category': 'shoes', 
        'sub_categories': ['womensshoes', 'mensshoes'],
        'mapkey': 'FootActionUSA',
        },  
    'footlocker': {
        'store_name': 'Foot Locker', 
        'store_category': 'shoes', 
        'sub_categories': ['womensshoes', 'mensshoes'],
        'mapkey': '???',
        },  
    'fragranza': {
        'store_name': 'Fragranza', 
        'store_category': 'healthandbeauty', 
        'sub_categories': ['cologneperfume'],
        'mapkey': 'Fragranza',
        },
    'frogurt': {
        'store_name': 'Frogurt', 
        'store_category': 'food', 
        'sub_categories': ['snacks'],
        'mapkey': 'outside',
        },
    'gamegridarcade': {
        'store_name': 'Game Grid Arcade', 
        'store_category': 'electronics', 
        'sub_categories': ['videogames'],
        'mapkey': 'GameGridArcade',
        },
    'gamepeddler': {
        'store_name': 'The Game Peddler', 
        'store_category': 'electronics', 
        'sub_categories': ['videogames'],
        'mapkey': 'TheGamePeddler',
        },  
    'gnc': {
        'store_name': 'GNC', 
        'store_category': 'healthandbeauty', 
        'sub_categories': ['health'],
        'mapkey': 'GNC',
        },
    'greekkabob': {
        'store_name': 'Greek Kabob', 
        'store_category': 'food', 
        'sub_categories': ['mediterranean'],
        'mapkey': 'GreekKabob',
        },
    'hammond': {
        'store_name': 'Hammond', 
        'store_category': 'gifts', 
        'sub_categories': ['toys'],
        'mapkey': 'Hammond',
        },  
    'hotdogstick': {
        'store_name': 'Hot Dog on a Stick', 
        'store_category': 'food', 
        'sub_categories': ['snacks'],
        'mapkey': 'HotDogStick',
        },
    'ikustomz': {
        'store_name': 'iKUSTOMZ', 
        'store_category': 'electronics', 
        'sub_categories': ['phoneaccessories'],
        'mapkey': '???',
        },  
    'jambajuice': {
        'store_name': 'Jamba Juice', 
        'store_category': 'food', 
        'sub_categories': ['juice'],
        'mapkey': 'outside',
        },
    'jbvariety': {
        'store_name': 'JB Variety', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing',
            'mensclothing', 'boysclothing', ],
        'mapkey': 'JBVariety',
        },  
    'jcpenney': {
        'store_name': 'J.C. Penney', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing', 
            'mensclothing', 'boysclothing', 'babyclothing', ],
        'mapkey': 'JCPenney',
        },
    'jimmyjohns': {
        'store_name': "Jimmy John's", 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkey': 'outside',
        },
    'jolene': {
        'store_name': "Jolene's Girl's Dresses", 
        'store_category': 'clothing', 
        'sub_categories': ['girlsclothing'],
        'mapkey': 'JolenesGirlsDresses',
        },
    'journeys': {
        'store_name': "Journey's", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing',
            'mensclothing', 'boysclothing'],
        'mapkey': 'Journeys',
        },
    'joyeria': {
        'store_name': "Joyeria", 
        'store_category': 'jewelry', 
        'sub_categories': ['everyday'],
        'mapkey': '???',
        },  
    'kayjewelers': {
        'store_name': "Kay Jewelers", 
        'store_category': 'jewelry', 
        'sub_categories': ['fine'],
        'mapkey': '???',
        },
    'kidsfashion': {
        'store_name': "Kid's Fashion", 
        'store_category': 'clothing', 
        'sub_categories': ['girlsclothing', 'boysclothing'],
        'mapkey': 'KidsFashion',
        },
    'lacuts': {
        'store_name': 'L.A. Cuts', 
        'store_category': 'healthandbeauty', 
        'sub_categories': ['hair'],
        'mapkey': 'LACuts',
        },
    'lhmmegaplex': {
        'store_name': 'Larry H. Miller Megaplex', 
        'store_category': 'movies', 
        'sub_categories': ['imax', 'standard'],
        'mapkey': 'Megaplex',
        },
    'macys': {
        'store_name': "Macy's", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing',
            'mensclothing', 'boysclothing', 'babyclothing', ],
        'mapkey': 'Macys',
        },
    'maurices': {
        'store_name': "Maurice's", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkey': 'Maurices',
        },
    'mdphotography': {
        'store_name': 'MD Photography', 
        'store_category': 'gifts', 
        'sub_categories': ['photography'],
        'mapkey': 'MDPhotography',
        },  
    'modabella': {
        'store_name': "Moda Bella", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkey': 'ModaBella',
        },
    'morganjewelers': {
        'store_name': "Morgan Jewelers", 
        'store_category': 'jewelry', 
        'sub_categories': ['fine'],
        'mapkey': 'MorganJewelers',
        },
    'movies9': {
        'store_name': 'Movies 9', 
        'store_category': 'movies', 
        'sub_categories': ['standard'],
        'mapkey': 'Movies9A',
        },
    'mrscav': {
        'store_name': "Mrs. Cavanaugh's", 
        'store_category': 'food', 
        'sub_categories': ['snacks'],
        'mapkey': '???',
        },
    'nerdstore': {
        'store_name': 'The Nerd Store', 
        'store_category': 'gifts', 
        'sub_categories': ['collectibles'],
        'mapkey': 'TheNerdStore',
        },  
    'nikkisbridal': {
        'store_name': "Nikki's Bridal", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkey': 'NikkisBridal',
        },
    'olivegarden': {
        'store_name': "Olive Garden", 
        'store_category': 'food', 
        'sub_categories': ['mediterranean'],
        'mapkey': 'outside',
        },
    'orangejulius': {
        'store_name': 'Orange Julius', 
        'store_category': 'food', 
        'sub_categories': ['juice'],
        'mapkey': 'OrangeJulius',
        },
    'osakajapan': {
        'store_name': 'Osaka Japan', 
        'store_category': 'food', 
        'sub_categories': ['asian'],
        'mapkey': 'OsakaJapan',
        },
    'passionnails': {
        'store_name': 'Passion Nails', 
        'store_category': 'healthandbeauty', 
        'sub_categories': ['nails'],
        'mapkey': 'PassionNails',
        },
    'payless': {
        'store_name': 'Payless Shoe Source', 
        'store_category': 'shoes', 
        'sub_categories': ['womensshoes', 'mensshoes'],
        'mapkey': 'PaylessShoeSource',
        },
    'petco': {
        'store_name': 'PetCo', 
        'store_category': 'home', 
        'sub_categories': ['pets'],
        'mapkey': 'outside',
        },
    'popcorncottage': {
        'store_name': 'Popcorn Cottage', 
        'store_category': 'food', 
        'sub_categories': ['snacks'],
        'mapkey': 'PopcornCottage',
        },
    'pretzelmaker': {
        'store_name': 'Pretzel Maker', 
        'store_category': 'food', 
        'sub_categories': ['snacks'],
        'mapkey': 'PretzelMaker1',
        },
    'purseplus': {
        'store_name': 'Purse Plus', 
        'store_category': 'accessories', 
        'sub_categories': ['purses'],
        'mapkey': 'PursePlus',
        },  
    'radioshack': {
        'store_name': 'RadioShack', 
        'store_category': 'electronics', 
        'sub_categories': ['computers', 'phoneaccessories', 'cellphones'],
        'mapkey': 'RadioShack',
        },  
    'rave': {
        'store_name': 'Rave', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkey': 'Rave'
        },
    'redrobin': {
        'store_name': 'Red Robin', 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkey': 'RedRobin',
        },
    'ricevillage': {
        'store_name': 'Rice Village', 
        'store_category': 'food', 
        'sub_categories': ['asian'],
        'mapkey': 'RiceVillage',
        },
    'ross': {
        'store_name': 'ROSS', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing',
            'mensclothing', 'boysclothing', 'babyclothing', ],
        'mapkey': 'ROSS'
        },
    'rue21': {
        'store_name': 'rue 21', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkey': 'UrbanExpress',
        },
    'rumbi': {
        'store_name': 'Rumbi', 
        'store_category': 'food', 
        'sub_categories': ['asian'],
        'mapkey': 'outside',
        },
    'ryanscustomjewelry': {
        'store_name': "Ryan's Custom Jewelry", 
        'store_category': 'jewelry', 
        'sub_categories': ['watches', 'fine'],
        'mapkey': 'RyansCustomJewelry',
        },
    'schubachjewelers': {
        'store_name': "Schubach Jewelers", 
        'store_category': 'jewelry', 
        'sub_categories': ['fine'],
        'mapkey': 'SchubachJewelers',
        },
    'shoemania': {
        'store_name': 'Shoe Mania', 
        'store_category': 'shoes', 
        'sub_categories': ['womensshoes', 'mensshoes'],
        'mapkey': '???',
        },
    'shoeoutlet': {
        'store_name': 'Shoe Outlet', 
        'store_category': 'shoes', 
        'sub_categories': ['womensshoes', 'mensshoes'],
        'mapkey': 'ShoeOutlet',
        },
    'silverloft': {
        'store_name': "Silver Loft", 
        'store_category': 'jewelry', 
        'sub_categories': ['everyday'],
        'mapkey': '???',
        },  
    'smashburger': {
        'store_name': 'Smashburger', 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkey': 'outside',
        },
    'sprint': {
        'store_name': 'Sprint', 
        'store_category': 'electronics', 
        'sub_categories': ['cellphones'],
        'mapkey': '???',
        },
    'subway': {
        'store_name': 'Subway', 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkey': 'Subway',
        },
    'sushimonster': {
        'store_name': 'Sushi Monster', 
        'store_category': 'food', 
        'sub_categories': ['asian'],
        'mapkey': 'outside',
        },
    'sweet16': {
        'store_name': "Sweet 16", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing'],
        'mapkey': '???',
        },
    'sweettoothfairy': {
        'store_name': 'Sweet Tooth Fairy', 
        'store_category': 'food', 
        'sub_categories': ['snacks'],
        'mapkey': 'outside',
        },
    'tgifridays': {
        'store_name': 'TGI Fridays', 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkey': 'outside',
        },
    'tieoneon': {
        'store_name': 'Tie One On', 
        'store_category': 'accessories', 
        'sub_categories': ['neckwear'],
        'mapkey': 'TieOneOn',
        },  
    'tmobile': {
        'store_name': 'T-Mobile', 
        'store_category': 'electronics', 
        'sub_categories': ['cellphones'],
        'mapkey': 'TMobile',
        },
    'trinketstreasures': {
        'store_name': "Trickets n' Treasures", 
        'store_category': 'gifts', 
        'sub_categories': ['miscgifts'],
        'mapkey': 'Trinkets&Treasures',
        },
    'tropicaljuice': {
        'store_name': 'Tropical Juice', 
        'store_category': 'food', 
        'sub_categories': ['juice'],
        'mapkey': 'TropicalJuice',
        },
    'ulta': {
        'store_name': 'Ulta Beauty', 
        'store_category': 'home', 
        'sub_categories': ['home'],
        'mapkey': 'Ulta',
        },
    'uniquegifts': {
        'store_name': "Unique Gifts", 
        'store_category': 'gifts', 
        'sub_categories': ['miscgifts'],
        'mapkey': 'UniqueGifts',
        },  
    'urbanexpress': {
        'store_name': 'Urban Express', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkey': 'UrbanExpress',
        },
    'westvalleymusic': {
        'store_name': "West Valley Music", 
        'store_category': 'gifts', 
        'sub_categories': ['musicalinst'],
        'mapkey': 'WestValleyMusic',
        },
    'wingers': {
        'store_name': "Winger's", 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkey': 'outside',
        },
    'xbrands': {
        'store_name': 'X-Brands Custom T-Shirts', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing',
            'mensclothing', 'boysclothing'],
        'mapkey': 'X-BrandsCustom',
        },
    'xzone': {
        'store_name': 'X-Zone', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing','mensclothing'],
        'mapkey': 'XZone',
        },
    'zagg': {
        'store_name': 'ZAGG', 
        'store_category': 'electronics', 
        'sub_categories': ['phoneaccessories'],
        'mapkey': 'ZAGG',
        },  
    'zumiez': {
        'store_name': 'Zumiez', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing',
            'mensclothing', 'boysclothing'],
        'mapkey': 'Zumeiz',
        },
    }
